# The locale to use while translating chat messages.
# Default value: en_US.
locale: "en_US"
# Options for spawning the cave spiders.
spawnOptions:
  # Spawning height range.
  range:
    # The minimum Y level that cave spiders will spawn.
    # Default value: -64
    minY: -64
    # The maximum Y level that cave spiders will spawn.
    # Default value: -8
    maxY: -8
    # Allow spiders to spawn below the minimum Y height.
    # This is useful for customizing the spawn distribution ramp function; spawns below the minimum Y value are
    #   guaranteed to use a constant spawn chance as set in the chances section below.
    # Defaults to false.
    allowSpawnsBelowMinY: false
  # Spawn distribution function. Affects how often cave spiders spawn in the world.
  # Valid values are constant, hyperbolic, linear, and logarithmic
  # In order of slowest to quickest ramp-up speed:
  # - Hyperbolic distribution ramps up slowly at first but increases in likelihood the further down you go.
  # - Linear distribution ramps up at a constant rate the further down you go.
  # - Logarithmic distribution ramps up very quickly at first but slows down the further down you go.
  # - Constant distribution is the same no matter what depth the spider is spawning at.
  # Defaults to constant.
  distribution: constant
  # Chances that a cave spider will replace a normal spider within the given range.
  # Settings are between 0 and 1, separated by difficulty level.
  chances:
    # Easy mode spawn rates.
    # Default value: 0.05, or 1 in 20.
    easy: 0.05
    # Normal mode spawn rates.
    # Default value: 0.1, or 1 in 10.
    normal: 0.1
    # Hard mode spawn rated.
    # Default value: 0.5, or 1 in 2.
    hard: 0.5
  # Chance for a cave spider to spawn a baby zombie as a rider.
  # Only applies on Hard difficulty.
  # Values are between 0 and 1.
  # Defaults to 0.1, or 1 in 10 cave spiders.
  jockeyChance: 0.1
# Biomes in which the cave spiders will spawn.
# Valid values: https://papermc.io/javadocs/paper/1.18/org/bukkit/block/Biome.html
biomes:
  - badlands
  - bamboo_jungle
  - birch_forest
  - dark_forest
  - desert
  - flower_forest
  - forest
  - grove
  - jagged_peaks
  - jungle
  - meadow
  - plains
  - savanna
  - savanna_plateau
  - sparse_jungle
  - stony_peaks
  - sunflower_plains
  - swamp
  - windswept_forest
  - windswept_gravelly_hills
  - windswept_hills
  - windswept_savanna
  - wooded_badlands
# The environments in which cave spiders will spawn.
# By default, only affects NORMAL environments.
# Valid values: https://papermc.io/javadocs/paper/1.18/org/bukkit/World.Environment.html
environments:
  - normal
# A list of all of the entity types that cave spiders can replace.
# Defaults to include only spiders.
# Only replaces natural spawns.
# Valid values: https://papermc.io/javadocs/paper/1.18/org/bukkit/entity/EntityType.html
replaceEntities:
  - spider
# Whether to show debug output in the console.
# Defaults to false.
debug: false
# Whether to send usage telemetry.
# Uses bStats (https://bstats.org)
# Defaults to false, initially set to true.
metrics: true
